# Generated by Django 4.2.3 on 2023-09-11 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_albumplaylist_options_alter_songs_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='album_playlist',
        ),
        migrations.DeleteModel(
            name='AlbumPlaylist',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
