# Generated by Django 4.2.3 on 2023-09-13 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_usersinclub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersinclub',
            name='club',
        ),
        migrations.RemoveField(
            model_name='usersinclub',
            name='user',
        ),
        migrations.DeleteModel(
            name='MusicClub',
        ),
        migrations.DeleteModel(
            name='UsersInClub',
        ),
    ]
