# Generated by Django 4.2.3 on 2023-09-15 19:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_userprofile_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='background_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='background_image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_image'),
        ),
    ]
