# Generated by Django 4.2.3 on 2023-09-26 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_userprofile_background_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlist_title',
            new_name='playlist_name',
        ),
        migrations.RenameField(
            model_name='songs',
            old_name='song_title',
            new_name='track_name',
        ),
    ]
