# Generated by Django 4.2.3 on 2023-09-28 21:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_userprofile_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Playlist Cover Image'),
        ),
    ]
