# Generated by Django 4.2.3 on 2023-09-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_playlist_playlist_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='spotify_username',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
