# Generated by Django 4.2.3 on 2023-10-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userprofile_spotify_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Songs',
            new_name='Track',
        ),
    ]
