# Generated by Django 4.2.3 on 2023-10-16 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0027_clubinvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubinvitation',
            unique_together={('user', 'club')},
        ),
    ]
