# Generated by Django 4.2.3 on 2023-07-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='weeks_per_user',
            field=models.CharField(choices=[('1', '1 Week'), ('2', '2 Weeks'), ('3', '3 Weeks')], default=2, max_length=1),
        ),
    ]
