# Generated by Django 4.2.3 on 2023-07-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='musicgroups',
            options={'verbose_name_plural': 'Music Groups'},
        ),
    ]
